config/routes.rb
Refriend::Application.routes.draw do
  resources :tasks do
    resources :references, only: %w(new create)
    post 'json', on: :collection
  end
  
  resources :references, only: %w(index edit edit update destroy)
  
  root to: 'tasks#index'
end

app/models/reference.rb
class Reference
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :referencer_uid
  field :referenced_uid
  field :description
  
  belongs_to :task
end

app/models/task.rb
class Task
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Document::Taggable
  
  
  
  field :title, type: String
  field :description, type: String
  field :cid, type: String
  field :requester_uid, type: String
  field :views_count, type: Integer, default: 0
  
  def view!;  self.update_attribute(:views_count, views_count + 1);  end
  
  has_many :references, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :set_headers, :current_person_uid, :current_person_cid
  protect_from_forgery with: :exception
  helper_method :current_person_uid, :current_person_cid
  
  
  
  def set_headers
    response.headers.delete('X-Frame-Options')
  end
  
  def current_person_cid
    if params[:query] && params[:query][:cid]
      session[:city_id] = params[:query][:cid]
    else
      session[:city_id]
    end
  end
  
  def current_person_uid
    session[:viewer_id] ||= params[:viewer_id]
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_filter :find_reference, only: %w(show edit destroy update)
  before_filter :find_task, except: %w(index)
  before_filter :new_reference, only: %w(create new)
  before_filter :find_references, only: %w(index)
  
  def new_reference;    @reference = Reference.new reference_params;  end
  def find_reference;   @reference = Reference.find params[:id];  end
  def find_references;  @references = Reference.all;  end
  def find_task;        @task = (@reference.task if @reference) || Task.find(params[:task_id]);  end
  
  # def update;           @reference.update_attributes(reference_params) ? redirect_to(@task) : render(:edit);  end
  # def destroy;          @reference.destroy ? redirect_to(@task) : render(text: 'faild');  end
  
  def create
    if @reference.save
      redirect_to @task, :notice => {
        referenced_uid: @reference.referenced_uid,
        message: "Рекомендация успешно размещена"
      }
    else
      render :new
    end
  end
  
  def reference_params
    unless params[:reference].blank?
      params.require(
        :reference
      ).permit(
        :description, :referenced_uid
      ).merge(
        referencer_uid: current_person_uid,
        task_id: @task.id
      )
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :new_task, only: %w(create new)
  before_filter :find_task, only: %w(show edit destroy update)
  before_filter :find_tasks, only: %w(index json)
  protect_from_forgery except: %w(json)
  helper_method :tag_list, :query, :scope, :selected_tags
    
  def new_task;     @task = Task.new task_params;  end
  def find_task;    @task = Task.find params[:id];  end
  def create;       @task.save ? redirect_to(@task) : render(:new);  end
  def update;       @task.update_attributes(task_params) ? redirect_to(root_url(query: {scope: 'own'})) : render(:edit);  end
  def show;         @task.view!;  end
  def destroy;      @task.destroy ? redirect_to(root_url(query: {scope: 'own'})) : render(text: 'faild');  end
  
  def json
    render json: {
      pagination: {
        pages: @tasks.total_pages,
        page: @tasks.current_page
      }, 
      tasks: @tasks.map{|t| {
        requester_uid: t.requester_uid,
        time: t.created_at.strftime('%H:%M'),
        date: t.created_at.strftime('%d/%m/%y'),
        title: t.title,
        cid: t.cid,
        id: t.id,
        tags: t.tags,
        views_count: t.views_count,
        references_count: t.references.count
      }}
    }.to_json
  end
  
  def find_tasks
    @tasks = Task.page(params[:page]).per(7)
    @tasks = @tasks.tagged_with_all(selected_tags) unless selected_tags.blank?
    @tasks = @tasks.where(cid: cid) if cid
    @tasks = @tasks.where(requester_uid: current_person_uid) if scope == 'own'
  end
  
  def tag_list
    Task.tag_list
  end
  
  
  def cid;              (query && query[:cid]) ? query[:cid] : nil;  end
  def scope;            (query && query[:scope]) ? query[:scope] : 'all';  end
  def selected_tags;    (query && query[:tags]) ? query[:tags] : [];  end
  def query;            params[:query];  end
  
  def task_params
    unless params[:task].blank?
      params.require(
        :task
      ).permit(
        :title, :description, :tag_list, :cid
      ).merge(
        requester_uid: current_person_uid
      )
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def new?
    action_name = 'new'
  end
  
  def edit?
    action_name = 'edit'
  end
  
  def active_if(condition)
    condition ? ' active' : ''
  end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_back.html.haml
%center
  = link_to root_url do
    Вернуться к списку объявлений
    %i.icon-arrow-left

app/views/layouts/_top_bar.html.haml
.navbar{'ng-controller' => 'Static'}
  .navbar-inner
    %ul.nav
      %li
        %img.navbar-avatar{src: "{{person(#{current_person_uid}).photo}}", alt: 'User avatar'}      
      %li.divider-vertical
      %li{class: active_if(controller_name == 'tasks')}
        %a{href: tasks_path} Объявления
      %li{class: active_if(controller_name == 'references')}
        %a{href: references_path} Рекоммендации

app/views/layouts/application.html.haml
!!! 5
%html{'ng-app' => true}
  %head
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
    %script{src: "http://vk.com/js/api/xd_connection.js?2", type: "text/javascript"}
    %link{href: 'http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=latin,cyrillic-ext,cyrillic', rel: 'stylesheet', type: 'text/css'}
    :javascript
      VK.init(function() {
        setTimeout(function(){
          VK.callMethod("resizeWindow", 800, document.height); 
        }, 2500)
      });
      currentPersonUid = "#{current_person_uid}";
%body{'ng-controller' => 'Static'}
  .container-fluid
    = yield

app/views/references/index.html.haml
%p.lead Я рекоммендую
- @references.where(referencer_uid: current_person_uid).each do |reference|
  = render 'references/units/my_reference', reference: reference

%p.lead Меня рекоммендуют
- @references.where(:referenced_uid => current_person_uid).each do |reference|
  = render 'references/units/my_reference', reference: reference

= render "layouts/back"

app/views/references/new.html.haml
%div{'ng-controller' => 'Static'}
  = render 'tasks/units/task', task: @task
  
= form_for @reference, url: task_references_path(@task) do |form|
  %fieldset.row-fluid
    - if params[:recommended] == 'self'
      %input{'type' => 'hidden', 'name' => 'reference[referenced_uid]', 'value' => current_person_uid}
    - if params[:recommended] == 'friend'
      %div{'ng-controller' => 'FriendSelect', 'ng-init' => "loadFriends(#{current_person_uid})"}
        %p Рекомендовать друга
        .well.well-small{'ng-show' => 'friends.length > 1'}
          %input{'type' => 'hidden', 'name' => 'reference[referenced_uid]', 'value' => '{{selectedFriend().uid}}'}  
          %input.span12{'type' => 'search', 'ng-model' => 'search', 'placeholder' => 'Поиск друга', 'ng-show' => "selectedFriend() == undefined"}
          %ul.unstyled.friends
            %li{'ng-repeat' => 'friend in friends | filter:search', 'ng-show' => 'show(friend)', 'ng-click' => "select(friend)"}
              %img{src: '{{friend.photo}}'}
              {{friend.first_name}} {{friend.nickname}} {{friend.last_name}}

    = form.label :description, 'Оставить комментарий'
    = form.text_area :description, rows: 6, class: 'span12'

  .form-actions
    = form.submit 'Рекомендовать', class: 'btn btn-primary'
    = link_to 'Отмена', task_path(@task), class: 'btn'  

= render 'layouts/back'

app/views/references/units/_my_reference.html.haml
%div.row-fluid.task
  %a.span2.text-center{'href' => "http://vk.com/id#{reference.referenced_uid}", 'target' => '_blank'}
    %br
    %img{src: "{{person(#{reference.referenced_uid}).photo}}"}
    %br
    {{person(#{reference.referenced_uid}).first_name}}
    {{person(#{reference.referenced_uid}).nickname}}
    {{person(#{reference.referenced_uid}).last_name}}
  .span1
    %br
    %br
    %i.icon-arrow-right
  .span2
    %img{src: "{{person(#{reference.task.requester_uid}).photo_big}}"}
  %a.span7{href: task_path(reference.task)}
    %ul.inline.pull-right
      %li
        %i.icon-map-marker
        %span {{city(#{reference.task.cid}).name}}
    %ul.inline
      %li
        {{person(#{reference.task.requester_uid}).first_name}}
        {{person(#{reference.task.requester_uid}).nickname}}
        {{person(#{reference.task.requester_uid}).last_name}}
      %li
        %i.icon-time
        = reference.task.created_at.strftime('%H:%M')
      %li
        %i.icon-calendar
        = reference.task.created_at.strftime('%d/%m/%y')
    %ul.inline
      %li
        %h4= reference.task.title
    %ul.inline.tags-cloud
      - reference.task.tags.each do |tag|
        %li.tag= tag

    

app/views/references/units/_reference.html.haml
.row-fluid
  - if reference.referencer_uid == reference.referenced_uid
    .span4
  .span2.text-center
    %a{'href' => "http://vk.com/id#{reference.referencer_uid}", 'target' => '_blank'}
      %img{src: "{{person(#{reference.referencer_uid}).photo}}"}
      %br
      {{person(#{reference.referencer_uid}).first_name}}
      {{person(#{reference.referencer_uid}).nickname}}
      {{person(#{reference.referencer_uid}).last_name}}
  - unless reference.referencer_uid == reference.referenced_uid
    .span2.text-center
      %br
      %i.icon-thumbs-up
      %br
      Рекоммендует
    .span2.text-center
      %a{'href' => "http://vk.com/id#{reference.referenced_uid}", 'target' => '_blank'}
        %img{src: "{{person(#{reference.referenced_uid}).photo}}"}
        %br
        {{person(#{reference.referenced_uid}).first_name}}
        {{person(#{reference.referenced_uid}).nickname}}
        {{person(#{reference.referenced_uid}).last_name}}
  
  .span6= reference.description

app/views/tasks/edit.html.haml
%p.lead Редактирование объявления
= render 'tasks/units/form', task: @task
= render 'layouts/back'

app/views/tasks/index.html.haml
%div{'ng-controller' => 'QueryForm'}

  - if scope != 'own'
    = render 'tasks/units/query_form'
  - else
    .pull-right= link_to 'Добавить объявление', new_task_path, class: 'btn btn-primary'
    %p.lead{"ng-init" => "scope = 'own'"} Мои объявления

  - if scope != 'own'
    %div
      %a.row-fluid.task{"ng-repeat" => "task in tasks", "href" => "/tasks/{{task.id.$oid}}"}
        .span2
          %img{src: "{{person(task.requester_uid).photo_big}}"}
        .span10
          %ul.inline.pull-right
            %li
              %i.icon-map-marker
              {{city(task.cid).name}}
          %ul.inline
            %li
              {{person(task.requester_uid).first_name}}
              {{person(task.requester_uid).nickname}}
              {{person(task.requester_uid).last_name}}
            %li
              %i.icon-time
              {{task.time}}
            %li
              %i.icon-calendar
              {{task.date}}
          %ul.inline
            %li
              %p.lead {{task.title}}
          %ul.inline.tags-cloud
            %li.tag{'ng-repeat' => 'tag in task.tags'} {{tag}}
  - else
    %div{"ng-repeat" => "task in tasks"}
      .row-fluid
        .span6
          %a{"href" => "/tasks/{{task.id.$oid}}"}
            %h5 {{task.title}}
        .span2.text-center
          %i.icon-eye-open
          %br
          Просмотров {{task.views_count}}
        .span2.text-center
          %i.icon-user
          %br
          Рекомендаций {{task.references_count}}
        .span1
          %a.btn{"href" => "/tasks/{{task.id.$oid}}/edit"}
            %i.icon-edit
        .span1
          %form{"action" => "/tasks/{{task.id.$oid}}", "method" => "post"}
            %input{"type" => "hidden", "value" => "delete", "name" => "_method"}
            %input.btn.btn-danger{"type" => "submit", "value" => "X"}
      %hr

  = render 'tasks/units/pager'
  
  - if scope == 'own'
    = render 'layouts/back'

app/views/tasks/new.html.haml
%p.lead Новое объявление
= render 'tasks/units/form', task: @task
= render 'layouts/back'

app/views/tasks/show.html.haml
= render 'tasks/units/task', task: @task

- if flash[:notice]
  %br
  .alert.alert-success= flash[:notice][:message]
  :javascript
    VK.init(function() { 
      VK.callMethod("showRequestBox", #{flash[:notice][:referenced_uid]}, 'Я рекомендовал тебя для объявления "#{@task.title}"', 0);
    });

- if current_person_uid == @task.requester_uid
  - unless @task.references.blank?
    %p.lead Рекоммендации
  - @task.references.each do |reference|
    = render 'references/units/reference', reference: reference
    
%hr
= render 'layouts/back'

app/views/tasks/units/_form.html.haml
= form_for task do |form|
  %fieldset.row-fluid
    .btn-group{"style" => "position: relative", "ng-init" => "preloadCity(#{current_person_cid})", 'ng-controller' => 'CitySelector'}
      %a.btn.dropdown-toggle{"href" => "#", "ng-click" => "cityComboBoxOpen = !cityComboBoxOpen", "ng-class" => "activeIf(cityComboBoxOpen)"}
        %input{"type" => "hidden", "value" => "{{selectedCity.cid}}", "name" => "task[cid]"}
        {{selectedCity.title}}
        %span.caret
      %ul.dropdown-menu{"style" => true, "ng-show" => 'cityComboBoxOpen'}
        %li
          %input{"type" => "text", "ng-model" => "citySearch", "placeholder" => 'Введите город', "style" => "width: "}
        %li{"ng-repeat" => "city in loadedCities"}
          %a{"href" => "#", "ng-click" => "selectCity(city)"}
            %ul.unstyled
              %li {{city.title}}
              %li
                %small {{city.region}}
          %hr
    %br
    %br
    = form.label :title, 'Название'
    = form.text_field :title, class: 'span12'

    = form.label :description, 'Описание'
    = form.text_area :description, rows: 6, class: 'span12'
    
    = form.label :tag_list, 'Добавить тег'
    %div{'ng-controller' => 'TagInput', 'ng-init' => "loadTags(#{tag_list.to_json})"}
      = form.hidden_field :tag_list, value: "{{selectedTags.join()}}"
      .span12{'ng-init' => "selectedTags = #{task.tags}"}
        %span.selected_tag{'ng-repeat' => 'tag in selectedTags', 'ng-click' => 'deselectTag(tag)'} {{tag}}
        %a{"href" => "#", "ng-click" => "clearTags()", "ng-show" => "selectedTags.length > 0"}Очистить
      .input-append
      .row-fluid{"ng-show" => "selectedTags.length < 3"}
        .input-append
          %input{"type" => "text", "ng-model" => "tagSearch", "placeholder" => "Поиск тега"}
          %a.btn{"href" => "#", 'ng-click' => 'add(tagSearch)'}
            %i.icon-plus
      .row-fluid{"ng-show" => "selectedTags.length < 3"}
        %ul.inline.tags-cloud
          %li.tag{'ng-repeat' => 'tag in tags | filter:tagSearch', "ng-click" => "selectTag(tag)"} {{tag}}

  .form-actions
    = form.submit 'Опубликовать', class: 'btn btn-primary'
    = link_to 'Отмена', root_url(query: {scope: 'own'}), class: 'btn'

app/views/tasks/units/_pager.html.haml
.pager{"ng-show" => "pages > 1"}
  %li{"ng-class" => "disabledIf(page == 1)"}
    %a{"href" => "#", "ng-click" => "pageDown()"} Предидущая
  %li Страница {{page}} из {{pages}}
  %li{"ng-class" => "disabledIf(page == pages)"}
    %a{"href" => "#", "ng-click" => "pageUp()"} Следующая

app/views/tasks/units/_query_form.haml
= form_for :query, method: :get do |form|
  .row-fluid
    .span3{"style" => "position: relative", "ng-init" => "preloadCity(#{current_person_cid})"}
      .btn-group
        %a.btn.dropdown-toggle{"href" => "#", "ng-click" => "cityComboBoxOpen = !cityComboBoxOpen", "ng-class" => "activeIf(cityComboBoxOpen)"}
          {{selectedCity.title}}
          %span.caret
        %ul.dropdown-menu{"style" => true, "ng-show" => 'cityComboBoxOpen'}
          %li
            %input{"type" => "text", "ng-model" => "citySearch", "placeholder" => 'Введите город', "style" => "width: "}
          %li{"ng-repeat" => "city in loadedCities"}
            %a{"href" => "#", "ng-click" => "selectCity(city)"}
              %ul.unstyled
                %li {{city.title}}
                %li
                  %small {{city.region}}
            %hr
          
          
    .span8{'ng-init' => "loadTags(#{tag_list.to_json})"}
      %span.selected_tag{'ng-repeat' => 'tag in selectedTags', 'ng-click' => 'deselectTag(tag)'} {{tag}}
      %a{"href" => "#", "ng-click" => "clearTags()", "ng-show" => "selectedTags.length > 0"}Очистить
    .span1
      .btn-group
        %a.btn-user.btn.dropdown-toggle{"href" => "#", "ng-click" => "userMenuOpen = !userMenuOpen", "ng-class" => "activeIf(userMenuOpen)"}
          %img{"src" => "{{person(#{current_person_uid}).photo}}"}
          %span.caret
        %ul.dropdown-menu{"style" => true, "ng-show" => 'userMenuOpen', "style" => "right: 0; left: auto"}
          %li
            %a{"href" => root_path(query: {scope: 'own'})} Мои объявления
          %li
            %a{"href" => references_path} Мои рекомендации
      
  %br
  
  .row-fluid{"ng-show" => "selectedTags.length < 3"}
    %input.span12{"type" => "text", "ng-model" => "tagSearch", "placeholder" => "Поиск тега"}
  .row-fluid{"ng-show" => "selectedTags.length < 3"}
    %ul.inline.tags-cloud
      %li.tag{'ng-repeat' => 'tag in tags | filter:tagSearch', "ng-click" => "selectTag(tag)"} {{tag}}
  .row-fluid
    .span12
      %center{'ng-init' => "scope = '#{scope}'"}
        %input{'type' => 'hidden', 'name' => 'query[scope]', 'value' => '{{scope}}'}
        .btn-group{"ng-init" => "scope = 'all'"}
          %a.btn{'ng-click' => 'scope = "all"', 'ng-class' => 'activeIf("all" == scope)'} Все объявления
          %a.btn{'ng-click' => 'scope = "friends"', 'ng-class' => 'activeIf("friends" == scope)'} Только друзей
          
          
          
%hr
.pull-right= link_to 'Добавить объявление', new_task_path, class: 'btn btn-primary'
%p.lead Порекоммендуйте друга...

app/views/tasks/units/_task.html.haml
.row-fluid
  .span2
    %img{src: "{{person(#{task.requester_uid}).photo_big}}"}
  .span10
    %ul.inline.pull-right
      %li
        %i.icon-map-marker
        {{city(#{task.cid}).name}}
    %ul.inline
      %li
        %a{href: "http://vk.com/id#{task.requester_uid}", target: "_blank"}
          {{person(#{task.requester_uid}).first_name}}
          {{person(#{task.requester_uid}).nickname}}
          {{person(#{task.requester_uid}).last_name}}
      %li
        %i.icon-time
        = task.created_at.strftime('%H:%M')
      %li
        %i.icon-calendar
        = task.created_at.strftime('%d/%m/%y')
    %ul.inline
      %li
        %p.lead= task.title
    %ul.inline.tags-cloud
      - task.tags.each do |tag|
        %li.tag= tag

.row-fluid
  %center
    %p.btn-group
      %a.btn.disabled
        %i.icon-eye-open
        = task.views_count
      %a.btn.disabled
        %i.icon-user
        = task.references.count
      
.row-fluid
  %p= task.description
= render 'tasks/units/task_menu', task: task

app/views/tasks/units/_task_menu.html.haml
%center
  = link_to 'Рекоммендовать себя', new_task_reference_path(task, recommended: 'self'), class: ('btn btn-primary' + active_if(params[:recommended] == 'self'))
  = link_to 'Рекоммендовать друга', new_task_reference_path(task, recommended: 'friend'), class: ('btn btn-primary' + active_if(params[:recommended] == 'friend'))
  / %a.btn.btn-primary{"href" => "#", "onclick" => ""}
  %br  